categories: [Sequence Analysis]
description: A tool to circularize genome assemblies
long_description: |
  Circlator will attempt to identify each circular sequence and output a linearised version of it. It does this by assembling all 
  reads that map to contig ends and comparing the resulting contigs with the input assembly. 
  The input assembly must not be too fragmented. Although Circlator will join contigs together, whenever it can identify contigs 
  that can be unambiguously joined, its main aim is to circularize the core genome and plasmids.
homepage_url: https://sanger-pathogens.github.io/circlator/ 
type: unrestricted
name: circlator
owner: leomrtns
