categories:
- Data Managers
- Sequence Analysis
description: Contains a data manager that defines and populates the MLST database for krocus
  tool data table.
homepage_url: https://github.com/thanhleviet/galaxy-tools
long_description: |
  Genome sequencing is rapidly being adopted in reference labs and hospitals for bacterial outbreak investigation and diagnostics where time is critical.
  Seven gene multi-locus sequence typing is a standard tool for broadly classifying samples into sequence types, allowing, in many cases, to rule a sample in or out of an outbreak, or allowing for general characteristics about a bacterial strain to be inferred.
  Long read sequencing technologies, such as from PacBio or Oxford Nanopore, can produce read data within minutes of an experiment starting, unlike short read sequencing technologies which require many hours/days. However, the error rates of raw uncorrected long read data are very high.
  We present Krocus which can predict a sequence type directly from uncorrected long reads, and which was designed to consume read data as it is produced, providing results in minutes. It is the only tool which can do this from uncorrected long reads.
  We tested Krocus on over 600 samples sequenced with using long read sequencing technologies from PacBio and Oxford Nanopore.
  It provides sequence types on average within 90 seconds, with a sensitivity of 94% and specificity of 97%, directly from uncorrected raw sequence reads.
  The software is written in Python and is available under the open source license GNU GPL version 3.
name: data_manager_build_krocus_database
owner: thanhlv
remote_repository_url: https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/data_managers/data_manager_build_krocus_mlst_database
type: unrestricted
