categories: [Sequence Analysis]
description: Comparative TraDIS analysis
long_description: |
  AlbaTraDIS is a software application for performing rapid large-scale comparative analysis of TraDIS experiments whilst also predicting the impact of inserts on nearby genes.
  It allows for experiements with multiple conditions to be easily analysed using statistical methods developed in the Bio-TraDIS toolkit.
homepage_url: https://github.com/quadram-institute-bioscience/galaxy-tools
name: albatradis
owner: thanhlv
remote_repository_url: https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/albatradis
type: unrestricted
