categories: [Sequence Analysis]
description: Order and orientation of complete bacterial genomes
long_description: |
  Socru allows you to easily identify and communicate the order and orientation of complete genomes around ribosomal operons.
  These large scale structural variants have real impacts on the phenotype of the organism, and with the advent of long read sequencing, we can now start to delve into the mechanisms at work.
homepage_url: https://github.com/quadram-institute-bioscience/galaxy-tools
name: socru
owner: thanhlv
remote_repository_url: https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/socru
type: unrestricted
