categories: [Sequence Analysis]
description: Long read spoligotyping for Mycobacterium tuberculosis.
long_description: |
  Galru allows for rapid spoligotyping for Mycobacterium tuberculosis directly
  from long read sequencing. It is fast and accurate. It requires a minimal
  amount of information to produce a spoligotype, and allows for near real-time
  typing when used to process sequencing data as it is produced by a Nanopore
  sequencer.
homepage_url: https://github.com/quadram-institute-bioscience/galru
name: galru
owner: thanhlv
remote_repository_url: https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/galru
type: unrestricted
