categories: [Sequence Analysis]
description: Galru is a Python 3 program that defines CRISPR spacer repertoire directly from uncorrected metagenomic long reads.
long_description: |
  Galru first identifies long reads that map to CRISPR-associated genes and searches along the read for the CRISPR spacer array. This array is compared to a database of known arrays to identify the sequence type (MLST).
homepage_url: https://github.com/quadram-institute-bioscience/galru
name: galru
owner: thanhlv
remote_repository_url: https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/galru
type: unrestricted
