categories: [Phylogenetics]
description: A toolkit for assigning objective taxonomic classifications to bacterial  and archaeal genomes
long_description: |
  GTDB-Tk is a software toolkit for assigning objective taxonomic classifications to bacterial and archaeal genomes. It
  is designed to work with recent advances that allow hundreds or thousands of metagenome-assembled genomes (MAGs) to be
  obtained directly from environmental samples. It can also be applied to isolate and single-cell genomes. The GTDB-Tk
  is open source and released under the GNU General Public License (Version 3).
name: gtdbtk
owner: leomrtns
homepage_url: https://github.com/Ecogenomics/GTDBTk 
remote_repository_url:  https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/gtdbtk 
