categories: [Sequence Analysis]
description: Antimicrobial Resistance Identification By Assembly
long_description: Antimicrobial Resistance Identification By Assembly
homepage_url: https://github.com/quadram-institute-bioscience/galaxy-tools
name: ariba
owner: thanhlv
remote_repository_url: https://github.com/sanger-pathogens/ariba
exclude:
  - planemo_command
  - ariba_prepareref.xml
  - ariba_pubmlstspecies.xml
  - help-command.txt
  - database
  - data_manager_build_ariba_database
  - test.ipynb
  - LICENSE.md