name: minipolish
owner: thanhlv
categories:
  - Sequence Analysis
description: A tool for Racon polishing of miniasm assemblies
homepage_url: https://github.com/rrwick/minipolish
long_description: |
  Miniasm is a great long-read assembly tool: straight-forward, effective and very fast. However, it does not include a polishing step, so its assemblies have a high error rate – they are essentially made of stitched-together pieces of long reads. Racon is a great polishing tool that can be used to clean up assembly errors. It's also very fast and well suited for long-read data. However, it operates on FASTA files, not the GFA graphs that miniasm makes. That's where Minipolish comes in. With a single command, it will use Racon to polish up a miniasm assembly, while keeping the assembly in graph form.
remote_repository_url: https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/minipolish
type: unrestricted
