categories: [Sequence Analysis]
description: Convert AMR gene detection tool output to hAMRonization specification format.
long_description: |
  Convert AMR gene detection tool output to hAMRonization specification format, combine the outputs of disparate antimicrobial resistance gene detection tools into a single unified format.
name: hamronization
owner: thanhlv
homepage_url: https://github.com/pha4ge/hAMRonization 
remote_repository_url:  https://github.com/quadram-institute-bioscience/galaxy-tools/tree/master/tools/hamronization 
